version: '3'
services:
  database:
    image: postgres:10-alpine
    env_file: .env
    ports:
    - "5432:5432"
    volumes:
    - database_volume:/var/lib/postgresql/data
volumes:
  database_volume: {}